spring:
    jpa:
        database: POSTGRESQL
        show-sql: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            dialect: org.hibernate.dialect.PostgreSQL9Dialect
    datasource:
        driverClassName: org.postgresql.Driver
# locally
#        url: jdbc:postgresql://localhost/msaas
# heroku:
        url: jdbc:postgresql://ec2-107-20-166-127.compute-1.amazonaws.com:5432/d60sg0hsmavm1d
        username: vwarfasctojfxo
        password: Xb0Clri3cCng1jJNFnGgBufOO4
    dao:
      exceptiontranslation:
        enabled: true

logging.level: INFO

# this is configured as an environment variable by heroku
server:
    port: ${port:7777}

---

spring:
  profiles: test

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:notification

  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect

logging.level.org.springframework.jdbc.core: TRACE