spring:
    jpa:
        database: POSTGRESQL
        show-sql: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            dialect: org.hibernate.dialect.PostgreSQL9Dialect
    datasource:
        driverClassName: org.postgresql.Driver
# locally
#        url: jdbc:postgresql://localhost/postgres
# heroku:
        url: jdbc:postgresql://ec2-107-20-166-127.compute-1.amazonaws.com:5432/d60sg0hsmavm1d
        username: vwarfasctojfxo
        password: Xb0Clri3cCng1jJNFnGgBufOO4
    dao:
      exceptiontranslation:
        enabled: true

logging.level: INFO

# this is configured as an environment variable by heroku
server:
    port: ${port:7777}

